name: smart_strength_coach
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^8.0.5
  video_player: ^2.9.2
  crypto: ^3.0.3
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
